version: '2'
services:
  mysql:
    container_name: flask_mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
      MYSQL_USER: 'horti'
      MYSQL_PASS: 'horti'
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: